move to go-flags, use basic docker builds

diff --git a/src/todo/Dockerfile b/src/todo/Dockerfile
--- a/src/todo/Dockerfile
+++ b/src/todo/Dockerfile
@@ -1,10 +1,22 @@
-FROM golang:1.12-rc-alpine
-RUN apk add --no-cache git gcc musl-dev
+FROM umputun/baseimage:buildgo-latest as build-backend
+#RUN apk add --no-cache gcc musl-dev
 WORKDIR /src/app
 COPY . .
-RUN go mod download
+RUN GO111MODULE=on go mod vendor
 RUN GOOS=linux GO111MODULE=on go build -o /app .
 
-FROM alpine:3.8
+FROM umputun/baseimage:app-latest
 COPY --from=0 /app /app
-ENTRYPOINT ["/app"]
+
+RUN chown -R app:app /app
+
+ADD entrypoint.sh /entrypoint.sh
+RUN chmod +x /entrypoint.sh
+
+EXPOSE 8080
+EXPOSE 2339
+
+#HEALTHCHECK --interval=30s --timeout=3s CMD curl --fail http://localhost:8080/ping || exit 1
+
+CMD ["server"]
+ENTRYPOINT ["/entrypoint.sh"]
